/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/chat-zh': RouteRecordInfo<'/chat-zh', '/chat-zh', Record<never, never>, Record<never, never>>,
    '/collective-sponsor-onetime': RouteRecordInfo<'/collective-sponsor-onetime', '/collective-sponsor-onetime', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/giving-talks': RouteRecordInfo<'/giving-talks', '/giving-talks', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/podcasts': RouteRecordInfo<'/podcasts', '/podcasts', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/break-lines-in-js': RouteRecordInfo<'/posts/break-lines-in-js', '/posts/break-lines-in-js', Record<never, never>, Record<never, never>>,
    '/posts/composable-vue-vueconf-china-2021': RouteRecordInfo<'/posts/composable-vue-vueconf-china-2021', '/posts/composable-vue-vueconf-china-2021', Record<never, never>, Record<never, never>>,
    '/posts/eslint-config-inspector': RouteRecordInfo<'/posts/eslint-config-inspector', '/posts/eslint-config-inspector', Record<never, never>, Record<never, never>>,
    '/posts/evolution-of-shiki-v1': RouteRecordInfo<'/posts/evolution-of-shiki-v1', '/posts/evolution-of-shiki-v1', Record<never, never>, Record<never, never>>,
    '/posts/get-package-root': RouteRecordInfo<'/posts/get-package-root', '/posts/get-package-root', Record<never, never>, Record<never, never>>,
    '/posts/introducing-nuxt-devtools': RouteRecordInfo<'/posts/introducing-nuxt-devtools', '/posts/introducing-nuxt-devtools', Record<never, never>, Record<never, never>>,
    '/posts/introduction-to-vitest-vue-nation-2022': RouteRecordInfo<'/posts/introduction-to-vitest-vue-nation-2022', '/posts/introduction-to-vitest-vue-nation-2022', Record<never, never>, Record<never, never>>,
    '/posts/isomorphic-dirname': RouteRecordInfo<'/posts/isomorphic-dirname', '/posts/isomorphic-dirname', Record<never, never>, Record<never, never>>,
    '/posts/new-ways-to-vue-london-2021': RouteRecordInfo<'/posts/new-ways-to-vue-london-2021', '/posts/new-ways-to-vue-london-2021', Record<never, never>, Record<never, never>>,
    '/posts/new-ways-to-vue-taiwan-2021': RouteRecordInfo<'/posts/new-ways-to-vue-taiwan-2021', '/posts/new-ways-to-vue-taiwan-2021', Record<never, never>, Record<never, never>>,
    '/posts/now-and-future-devtools-nuxt-nation-2023': RouteRecordInfo<'/posts/now-and-future-devtools-nuxt-nation-2023', '/posts/now-and-future-devtools-nuxt-nation-2023', Record<never, never>, Record<never, never>>,
    '/posts/nuxt-devtools-v1': RouteRecordInfo<'/posts/nuxt-devtools-v1', '/posts/nuxt-devtools-v1', Record<never, never>, Record<never, never>>,
    '/posts/nuxt-dx-strasbourg-2023': RouteRecordInfo<'/posts/nuxt-dx-strasbourg-2023', '/posts/nuxt-dx-strasbourg-2023', Record<never, never>, Record<never, never>>,
    '/posts/patterns-of-vueuse-vuefes-japan-2022': RouteRecordInfo<'/posts/patterns-of-vueuse-vuefes-japan-2022', '/posts/patterns-of-vueuse-vuefes-japan-2022', Record<never, never>, Record<never, never>>,
    '/posts/pnpm-external-disk': RouteRecordInfo<'/posts/pnpm-external-disk', '/posts/pnpm-external-disk', Record<never, never>, Record<never, never>>,
    '/posts/range-in-javascript': RouteRecordInfo<'/posts/range-in-javascript', '/posts/range-in-javascript', Record<never, never>, Record<never, never>>,
    '/posts/refreshed-nuxt-eslint': RouteRecordInfo<'/posts/refreshed-nuxt-eslint', '/posts/refreshed-nuxt-eslint', Record<never, never>, Record<never, never>>,
    '/posts/roads-to-oss-progressive-vueams-2024': RouteRecordInfo<'/posts/roads-to-oss-progressive-vueams-2024', '/posts/roads-to-oss-progressive-vueams-2024', Record<never, never>, Record<never, never>>,
    '/posts/roads-to-oss-set-theory-react-paris-2024': RouteRecordInfo<'/posts/roads-to-oss-set-theory-react-paris-2024', '/posts/roads-to-oss-set-theory-react-paris-2024', Record<never, never>, Record<never, never>>,
    '/posts/roads-to-oss-set-theory-viteconf-2023': RouteRecordInfo<'/posts/roads-to-oss-set-theory-viteconf-2023', '/posts/roads-to-oss-set-theory-viteconf-2023', Record<never, never>, Record<never, never>>,
    '/posts/roads-to-oss-set-theory-vuefesjapan-2023': RouteRecordInfo<'/posts/roads-to-oss-set-theory-vuefesjapan-2023', '/posts/roads-to-oss-set-theory-vuefesjapan-2023', Record<never, never>, Record<never, never>>,
    '/posts/vite-on-demand-dx-viteconf-2022': RouteRecordInfo<'/posts/vite-on-demand-dx-viteconf-2022', '/posts/vite-on-demand-dx-viteconf-2022', Record<never, never>, Record<never, never>>,
    '/posts/vueuse-best-practice-vueconf-china-2022': RouteRecordInfo<'/posts/vueuse-best-practice-vueconf-china-2022', '/posts/vueuse-best-practice-vueconf-china-2022', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/sponsors-list': RouteRecordInfo<'/sponsors-list', '/sponsors-list', Record<never, never>, Record<never, never>>,
    '/streams': RouteRecordInfo<'/streams', '/streams', Record<never, never>, Record<never, never>>,
    '/talks': RouteRecordInfo<'/talks', '/talks', Record<never, never>, Record<never, never>>,
  }
}
